apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sidecar-injector
commonLabels:
  app.kubernetes.io/instance: sidecar-injector
images:
  - name: sidecar-injector
    newName: sidecar-injector
    newTag: v0.0.1
resources:
  - service-account.yaml
#  - rbac.yaml
  - tls.yaml
  - deployment.yaml
  - service.yaml
  - mutating-webhook-configuration.yaml
