apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: sidecar-injector
  labels:
    app: sidecar-injector
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "configmaps" ]
    verbs: [ "*" ]
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "mutatingwebhookconfigurations" ]
    verbs: [ "create", "get", "delete", "list", "patch", "update", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "developer" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: sidecar-injector
  labels:
    app: sidecar-injector
subjects:
  - kind: ServiceAccount
    name: sidecar-injector # Name is case sensitive
    namespace: sidecar-injector
roleRef:
  kind: ClusterRole
  name: sidecar-injector
  apiGroup: rbac.authorization.k8s.io
