apiVersion: v1
kind: Service
metadata:
  name: sidecar-injector
spec:
  selector:
    app: sidecar-injector
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
    - protocol: TCP
      port: 443
      targetPort: https
      name: https
  type: ClusterIP
  